name: My first Github Workflow
on: [push]
jobs:
  docker_python_version:
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: python --version
      - name: Check docker and python version
			 
